### ISSUE TITLE
AWS Free-tier 발급 받고, 설정하기

### ISSUE THREAD

**Issue by FlabKenneth** [f-lab-edu/youtube-question-generation#9]
## 목적

- 만든 서비스를 배포하기 위해서 클라우드 계정을 발급 받고, 클라우드를 통해 도커 이미지를 배포해서 구동하는 작업을 진행한다.

## 할 일

- [x] AWS 계정 가입 및 카드 정보 등록해서 Free-tier 사용할 수 있도록 준비.
- [x] AWS EC2 Ubuntu로 실행 시키고, Docker 설치해두기. [설치 가이드](https://docs.docker.com/engine/install/ubuntu/) 참조.
- [x] AWS RDS 설정하기 (MySQL).

**Comment by rimiyeyo** [comment]
-aws https://jongsky.tistory.com/49

**Comment by rimiyeyo** [comment]
[2] 1. AWS EC2 실행
     2. 탄력적 IP 실행 ([1,2번 참고글](https://rachel0115.tistory.com/entry/AWS-EC2-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%83%9D%EC%84%B1-%EB%B0%8F-%EC%84%A4%EC%A0%95))
     3. YUM 설치?

**Comment by rimiyeyo** [comment]
[AWS LINUX docker install reference](https://jinjinyang.tistory.com/46)

**Comment by rimiyeyo** [comment]
질문) AWS EC2 인스턴스 생성할 때 꼭 탄력적IP를 설정해줘야하는건가? 탄력적 IP를 쓰지 않고 public IP 사용하면 안되는건가?

**Comment by rimiyeyo** [comment]
- [RDS 생성 후 EC2 와 연동](https://bcp0109.tistory.com/357)
